apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-daemonset
  namespace: instana-agent
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "patch"]